#!/usr/bin/env bash

# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

compile() {
    check_dependency_dotnet

    cd $APP_HOME
    header "Running tests..."
    PROJECTS=$(dotnet sln reverse-proxy.sln list | grep '\.Test')

    for PROJ in $PROJECTS; do
	    PROJ=${PROJ//\\/\/}
	    # Cleaning up special characters
    	PROJ=$(echo $PROJ | sed 's/[^a-zA-Z\.\/]//g')
	    echo "-- $PROJ"
	    dotnet test --configuration $CONFIGURATION $PROJ
    done
}

run_tests() {
    check_dependency_dotnet

    cd $APP_HOME
    header "Running tests..."
    PROJECTS=$(dotnet sln list | grep 'csproj$' | grep '\.Test')
    for PROJ in $PROJECTS; do
        echo "-- $PROJ"
        dotnet test --configuration $CONFIGURATION $PROJ
    done
}


# workaround for https://github.com/dotnet/cli/issues/3995
unset home

compile
run_tests

set +e
